"""addcolumns to Tournaments table: in_progress (int), in_progress_round (int), complete (bool)

Revision ID: 69ed2b3ae6cf
Revises: 03a46316239b
Create Date: 2022-09-02 18:46:30.787215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ed2b3ae6cf'
down_revision = '03a46316239b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('in_progress', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('in_progress_round', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('complete', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'matches', ['in_progress'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'complete')
    op.drop_column('tournaments', 'in_progress_round')
    op.drop_column('tournaments', 'in_progress')
    # ### end Alembic commands ###
