"""addcolumns to Tournaments table: in_progress (int), in_progress_round (int), complete (bool) without foreign key

Revision ID: 81045209b5e2
Revises: 69ed2b3ae6cf
Create Date: 2022-09-02 18:51:36.661518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81045209b5e2'
down_revision = '69ed2b3ae6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournaments_in_progress_fkey', 'tournaments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tournaments_in_progress_fkey', 'tournaments', 'matches', ['in_progress'], ['id'])
    # ### end Alembic commands ###
